### ISSUE TITLE
Create tv.cynkra.com subdomain

### ISSUE THREAD

**Issue by pat-s** [cynkra/tv#23]
Now that there is a pkgdown site.

**Comment by krlmlr** [comment]
Not sure this is sustainable. What about SSL certificates?

**Comment by pat-s** [comment]
> What about SSL certificates?

Let's encrypt from GitHub Pages.

**Comment by krlmlr** [comment]
Works now?

**Comment by christophsax** [comment]
Looks superb, also in ff:

https://tv.cynkra.com

**Comment by pat-s** [comment]
👏
